# General
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096
# Logging
CONFIG_LOG=y
# Network
CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_POSIX_API=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_CONNECTION_MANAGER_MONITOR_STACK_SIZE=4600
# Modem
CONFIG_NRF_MODEM_LIB=y
CONFIG_NRF_MODEM_LIB_NET_IF=y
CONFIG_MODEM_KEY_MGMT=y
CONFIG_LTE_LINK_CONTROL=y
# DNS
CONFIG_DNS_RESOLVER=y
# Hostname
# CONFIG_HTTPS_HOSTNAME="webhook.site"

#NCS version issue
CONFIG_LTE_LC_PSM_MODULE=y
CONFIG_LTE_PSM_REQ=y
CONFIG_LTE_LC_EDRX_MODULE=y

# Floating point support for CBPRINTF, needed for logging the radar data
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_CBPRINTF_FP_SUPPORT=y
#Debugging LTE connection failures, NCS version issue suspected
# CONFIG_NET_CONNECTION_MANAGER=y
# CONFIG_NET_CONNECTION_MANAGER_MONITOR_STACK_SIZE=4600

# Prevent reset cycle lockout
# CONFIG_LTE_LC_FUNC_MODE_MODULE=y

CONFIG_SERIAL=y
# CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SNTP=y
# eDRX settings timer table index for LTE-M, 20.48s cycle — should be shorter than UPDATE_RATE_MS
# CONFIG_LTE_LC_EDRX_REQ_VALUE_LTE_M="2"

#Solar Panel/Battery Support
CONFIG_NPM13XX_CHARGER=y
CONFIG_SENSOR=y